version: '3.8'
services:
  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    ports:
      - "8080:8080"
    environment:
      - BASE_URL=http://localhost:8080/
    volumes:
      - searxng_data:/etc/searxng
      - ./searxng.settings.yml:/etc/searxng/settings.yml:ro
    restart: unless-stopped
volumes:
  searxng_data:
