services:
  searxng:
    container_name: searxng
    image: searxng/searxng:latest
    ports:
      - "8080:8080"
    environment:
      - SEARXNG_BASE_URL=https://${SEARXNG_HOSTNAME:-localhost}/
    volumes:
      - searxng_data:/etc/searxng
      - ./searxng.settings.yml:/etc/searxng/settings.yml:ro
    restart: unless-stopped
volumes:
  searxng_data:
