# SearXNG basic configuration example
# For full options, see: https://docs.searxng.org/admin/settings/

use_default_settings: true

server:
  public_instance: true

general:
  instance_name: "Seer"
  privacypolicy_url: false
  donation_url: false
  contact_url: false
  enable_metrics: false

search:
  safe_search: 0
  autocomplete: "google"

engines:
  - name: google
    engine: google

ui:
  query_in_title: false
  infinite_scroll: true
  center_alignment: true
  cache_url: https://web.archive.org/web/
  default_theme: simple
  theme_args:
    simple_style: auto
  search_on_category_select: true
  hotkeys: default
  url_formatting: pretty

categories_as_tabs:
  general:
  images:
  videos:
  news:
  map:
  music:
  it:
  science:
  files:

plugins:
  searx.plugins.calculator.SXNGPlugin:
    active: true

  searx.plugins.hash_plugin.SXNGPlugin:
    active: true

  searx.plugins.self_info.SXNGPlugin:
    active: true

  searx.plugins.tracker_url_remover.SXNGPlugin:
    active: true

  searx.plugins.unit_converter.SXNGPlugin:
    active: true

  searx.plugins.hostnames.SXNGPlugin:
    active: true

  searx.plugins.oa_doi_rewrite.SXNGPlugin:
    active: true

hostnames:
  high_priority:
    - '(.*\.)?wikipedia.org$'
    - '(.*\.)?archive.org$'
    - "news.ycombinator.com$"
    - '(.*\.)?imdb.com$'
    - '(.*\.)?letterboxd.com$'
  remove:
    - '(.*\.)?facebook\.[a-z.]+$'
    - '(.*\.)?twitter\.[a-z.]+$'
    - '(.*\.)?pinterest\.[a-z.]+$'
    - '(.*\.)?timesofisrael\.[a-z.]+$'
    - '(.*\.)?dailymail\.[a-z.]+$'
    - '(.*\.)?quora\.[a-z.]+$'
    - '(.*\.)?githubplus\.[a-z.]+$'
    - '(.*\.)?tiktok\.[a-z.]+$'
